language: python
python:
 - 3.6
install:
 - cp contrib/env-sample .env
 - pip install -q -r requirements-dev.txt
script:
 - flake8
 - coverage run --source='charcoallog' manage.py test
 - coverage report
