languge: python
python:
 - 3.6
addons:
 apt:
   update: true
install:
 - pip install -q -r requirements-dev.txt
script:
 - flake8
 - coverage run --source='charcoallog' manage.py test
 - coverage report
