language: python
python:
 - 3.6
install:
 - cp contrib/env-sample .env
 - pip install -q -r requirements-dev.txt
before_script:
 - mv charcoallog project
script:
 - flake8
 - coverage run manage.py test -v 3
 - coverage report
