# Generated by Django 2.2.4 on 2019-08-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0020_auto_20190820_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvestmentdetails',
            name='quant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
