# Generated by Django 2.2.4 on 2019-08-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0021_auto_20190821_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvestmentdetails',
            name='segment',
            field=models.CharField(default='---', max_length=30),
        ),
    ]
